# Generated by Django 3.2.12 on 2023-07-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20230717_0212'),
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Missing Info'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(default='Missing Info', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Missing Info'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Missing Info'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='User 1', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(decimal_places=5, default=0.99999, max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.CharField(default='Missing Info', max_length=25),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(default='Missing Info', max_length=100),
        ),
    ]
