# Generated by Django 3.2.12 on 2023-07-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20230718_0047'),
        ('recipe_app', '0003_auto_20230717_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='saved_recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_recipes',
            field=models.ManyToManyField(null=True, to='user_app.User'),
        ),
    ]
