# Generated by Django 3.2.12 on 2023-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_friends'),
        ('recipe_app', '0005_alter_recipe_saved_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='saved_recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_recipes', to='user_app.User'),
        ),
    ]
