# Generated by Django 3.2.12 on 2023-07-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20230717_0212'),
        ('recipe_app', '0002_auto_20230717_0212'),
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_text',
            field=models.TextField(default='This recipe was great as is!!'),
        ),
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipe'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
    ]
