# Generated by Django 3.2.12 on 2023-07-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_auto_20230717_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='recipe_id',
        ),
    ]
