# Generated by Django 3.2.12 on 2023-07-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_rename_notes_note_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
