# Generated by Django 3.2.12 on 2023-07-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_auto_20230718_2321'),
        ('user_app', '0004_alter_user_friends'),
        ('note_app', '0004_rename_recipe_id_note_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='recipe_app.recipe'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to='user_app.user'),
        ),
    ]
