# Generated by Django 3.2.12 on 2023-07-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='User 1', max_length=25, unique=True),
        ),
    ]
