# Generated by Django 3.2.12 on 2023-07-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20230717_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_user_app_user_friends_+', to='user_app.User'),
        ),
    ]
